govc: Update CONTIRBUTING.md file
vmware/govmomi pull request #2709
Opened 2022-01-18 15:35 UTC by pradeep288

Closes: #2708

## Description

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List any dependencies that are required
for this change.

Closes: #(issue-number)

## Type of change

Please mark options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update
- [ ] Build related change

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. If applicable, please also list any relevant
details for your test configuration.

- [ ] Test Description 1
- [ ] Test Description 2

## Checklist:

- [ ] My code follows the CONTRIBUTION [guidelines](./../CONTRIBUTING.md) of
  this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

2022-01-18 15:48 UTC, embano1 requested changes
Minor change

2022-01-18 15:48 UTC, embano1 commented on CONTRIBUTING.md
> +To register the new `govc` command package, import package into `govmomi/govc/main.go` file.
```suggestion
To register the new `govc` command package, add a blank `_` import to `govmomi/govc/main.go`.
```

2022-01-18 19:33 UTC, embano1 reviewed
THX! Please squash and I'll approve.

2022-01-20 19:35 UTC, embano1 commented
Something seems wrong with the commit.

Please also note that:

- There's a typo in the commit title
- Please use the `docs: ` prefix in the commit title for proper CHANGELOG rendering.

2022-01-22 16:45 UTC, pradeep288 commented
> Something seems wrong with the commit.
> 
> Please also note that:
> 
> * There's a typo in the commit title
> * Please use the `docs: ` prefix in the commit title for proper CHANGELOG rendering.

Updated the commit message as per the above suggestion

2022-01-24 12:37 UTC, embano1 approved these changes
LGTM

2022-01-24 12:37 UTC, merged