vcsim: EnvironmentBrowser improvements
vmware/govmomi pull request #3083
Opened 2023-04-01 15:34 UTC by dougm

## Description

vcsim: add EnvironmentBrowser methods and record/replay support

api: add object.EnvironmentBrowser helper methods

govc: add vm.option.ls, vm.target.info and vm.target.cap.ls commands

BREAKING: removed object.VirtualMachine.QueryConfigTarget method
- Use object.VirtualMachine.EnvironmentBrowser().QueryConfigTarget instead

## Type of change

Please mark options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update
- [ ] Build related change

## How Has This Been Tested?

Added new bats tests.

## Checklist:

- [x] My code follows the `CONTRIBUTION`
  [guidelines](https://github.com/vmware/govmomi/blob/main/CONTRIBUTING.md) of
  this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

2023-09-27 17:46 UTC, akutz requested changes
The PR itself is fine, but I think the instances of the year `2022` need to be updated to `2023`. I stopped leaving a remark on each one, but I think it's consistently `2022` on any file that was touched.

2023-09-27 17:46 UTC, akutz commented on govc/flags/env.go
> +Copyright (c) 2022-2022 VMware, Inc. All Rights Reserved.
Wrong date?

2023-09-27 17:46 UTC, akutz commented on govc/object/save.go
> +Copyright (c) 2019-2022 VMware, Inc. All Rights Reserved.
2023?

2023-09-27 17:46 UTC, akutz commented on govc/vm/option/info.go
> +Copyright (c) 2019-2022 VMware, Inc. All Rights Reserved.
2023?

2023-09-27 17:46 UTC, akutz commented on govc/vm/option/ls.go
> +Copyright (c) 2022-2022 VMware, Inc. All Rights Reserved.
2023?

2023-09-27 17:46 UTC, akutz commented on govc/vm/rdm/ls.go
> +Copyright (c) 2017-2022 VMware, Inc. All Rights Reserved.
2023?

2023-09-27 17:46 UTC, akutz commented on govc/vm/target/capabilities.go
> +Copyright (c) 2022-2022 VMware, Inc. All Rights Reserved.
2023?

2023-09-27 17:46 UTC, akutz commented on govc/vm/target/info.go
> +Copyright (c) 2022-2022 VMware, Inc. All Rights Reserved.
2023?

2023-09-27 19:04 UTC, dougm commented
> The PR itself is fine, but I think the instances of the year `2022` need to be updated to `2023`. I stopped leaving a remark on each one, but I think it's consistently `2022` on any file that was touched.

I used scripts/license.sh to update the headers, it's 2022 because the original commit was 2022: https://patch-diff.githubusercontent.com/raw/vmware/govmomi/pull/3083.patch
```
Date: Mon, 12 Dec 2022 09:43:42 -0800
```
Suppoe I can change the commit date

2023-09-28 17:04 UTC, akutz approved these changes

2023-09-28 17:05 UTC, akutz commented
Thanks for the update. I did not realize the original PR was opened last year. Mea culpa.

2023-09-28 17:16 UTC, merged